### PR TITLE
[DMP-4375] Setting limit to 10k for number of rows from hive

### PR DESCRIPTION
**Pull request by satishjshinde**
[DMP-4375] Setting limit to 10k for number of rows from hive

### CODE REVIEW

**Comment by acockell** [comment]
@satishjshinde  - can we bump this up to 30k - 10k might be a bit too low

**Comment by satishjshinde** [comment]
@acockell done.

**Comment by tmitchellRedwoods** [comment]
Why are we merging into master instead of develop? Is it because it's an open source library that we forked? Please clarify.

**Comment by satishjshinde** [comment]
@tmitchellRedwoods Each repo follows its own conventions. We do have other patterns of branching in other products whereas here it is forked from open source library, shouldn't be dealing with branching patterns here.

**Pull request merged**
